[package]
name = "tmpctl"
version = "0.1.0"
license = "MIT"
edition = "2021"
authors = ["Daniil Novoselov <gudnmail@gmail.com>"]

[dependencies]
regex = "1"
lazy_static = "1"
clap = { version = "3", features = ["derive"] }
